# ================= ESS7 EXTENDED BOOTSTRAPPER =================

Write-Host "[ESS7] Initializing Extended Bootstrapper..." -ForegroundColor Cyan

$Root = "C:\EagleShield_PS7_Suite\ESS7-Bundle-Builder_files"

# --- Helpers ---
function New-ESS7Directory {
    param([string]$Path)
    if (!(Test-Path $Path)) { New-Item -ItemType Directory -Path $Path | Out-Null }
}

function Write-ESS7File {
    param([string]$Name, [string]$Content)
    $Path = Join-Path $Root $Name
    $Content | Set-Content $Path -Encoding ASCII
}

function Write-ESS7Log {
    param([string]$Message)
    $Log = Join-Path $Root "ESS7-Bootstrap.log"
    "$((Get-Date).ToString("yyyy-MM-dd HH:mm:ss")) `t $Message" | Add-Content $Log -Encoding ASCII
}

# --- Prepare root ---
New-ESS7Directory $Root
Write-ESS7Log "Bootstrapper started."

# --- Installers ---
Write-ESS7File "ESS7-Core-Installer.ps1" "Write-Host '[ESS7-CORE] Installing Core...'"
Write-ESS7File "ESS7-FullSystem-Installer.ps1" "Write-Host '[ESS7-FULL] Installing Full System...'"
Write-ESS7File "ESS7-Forensic-Installer.ps1" "Write-Host '[ESS7-FOR] Installing Forensic Suite...'"
Write-ESS7File "ESS7-OS-Integration-Installer.ps1" "Write-Host '[ESS7-OS] Installing OS Integration...'"
Write-ESS7File "ESS7-Unity-Binding-Installer.ps1" "Write-Host '[ESS7-UNITY] Installing Unity Binding...'"
Write-ESS7File "ESS7-VR-Deployer-Installer.ps1" "Write-Host '[ESS7-VR] Installing VR Deployer...'"
Write-ESS7File "ESS7-AEGENTIS-Runtime-Installer.ps1" "Write-Host '[ESS7-AEGENTIS] Installing Runtime...'"
Write-ESS7File "ESS7-DevSkeleton-Installer.ps1" "Write-Host '[ESS7-DEV] Installing Dev Skeleton...'"

# --- Docs ---
Write-ESS7File "README.txt" "ESS7 README ? Generated by Extended Bootstrapper."
Write-ESS7File "VERSION.txt" "ESS7 VERSION 1.0.0 ? EXTENDED CHANNEL"
Write-ESS7File "INSTALL_ORDER.txt" "Core ? Full ? Forensic ? OS ? Unity ? VR ? AEGENTIS ? Dev"
Write-ESS7File "MODE_MAP.txt" "CORE, FULL, FORENSIC, OS, UNITY, VR, AEGENTIS, DEV"
Write-ESS7File "THEME_GUIDE.txt" "Themes: DarkOps, WhiteGold, TerminalGlass, RetroGreen, Custom"

# --- Theme Engine ---
Write-ESS7File "ESS7-ThemeEngine.ps1" @"
param([string]`$Theme='DarkOps')
switch (`$Theme) {
    'DarkOps' { @{Background='#050608';Foreground='#F5F7FA';Accent='#00D1FF'} }
    'WhiteGold' { @{Background='#FDFBF7';Foreground='#1A1A1A';Accent='#C9A227'} }
    'TerminalGlass' { @{Background='#050608';Foreground='#00FF9C';Accent='#00D1FF'} }
    'RetroGreen' { @{Background='#020502';Foreground='#00FF00';Accent='#00AA00'} }
    default { @{Background='#101010';Foreground='#FFFFFF';Accent='#FF4081'} }
}
"@

# --- VR Mode Detector ---
Write-ESS7File "ESS7-VR-Mode.ps1" "return `$false"

# --- GUI ---
Write-ESS7File "ESS7-GUI.ps1" @"
Add-Type -AssemblyName PresentationFramework
`$theme = & (Join-Path (Split-Path `$MyInvocation.MyCommand.Path) 'ESS7-ThemeEngine.ps1')
`$window = New-Object System.Windows.Window
`$window.WindowStyle='None'
`$window.WindowState='Maximized'
`$window.Topmost=`$true
`$window.Content='ESS7 COMMAND CENTER ? EXTENDED'
`$window.ShowDialog() | Out-Null
"@

# --- Launcher ---
Write-ESS7File "ESS7-Launcher.ps1" @"
Write-Host 'ESS7 LAUNCHER'
Write-Host '1) GUI'
Write-Host '2) Terminal'
`$sel = Read-Host 'Select'
if (`$sel -eq '1') { powershell -File (Join-Path `$PSScriptRoot 'ESS7-GUI.ps1') }
if (`$sel -eq '2') { Get-ChildItem `$PSScriptRoot -Filter 'ESS7-*-Installer.ps1' }
"@

Write-ESS7Log "Bootstrapper finished."
Write-Host "[ESS7] Extended bootstrap complete." -ForegroundColor Cyan

# ================= END BOOTSTRAPPER =================
