import type { Pool } from 'pg';
import type { CapabilityMatch } from './types.js';
import type { CapabilityAsset, CapabilityRegistry } from './capability-indexer.js';

export class PostgresCapabilityRegistry implements CapabilityRegistry {
 constructor(private readonly pool:Pool){}
 async upsert(a:CapabilityAsset):Promise<void>{await this.pool.query(`insert into capability_assets(id,source_type,source_uri,name,description,maturity,execution_zones,tags,evidence,metadata_json,content_hash,discovered_at,updated_at) values($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9::jsonb,$10::jsonb,$11,$12,now()) on conflict(source_type,source_uri) do update set name=excluded.name,description=excluded.description,maturity=excluded.maturity,execution_zones=excluded.execution_zones,tags=excluded.tags,evidence=excluded.evidence,metadata_json=excluded.metadata_json,content_hash=excluded.content_hash,discovered_at=excluded.discovered_at,updated_at=now()`,[a.id,a.sourceType,a.sourceUri,a.name,a.description,a.maturity,JSON.stringify(a.executionZones),JSON.stringify(a.tags),JSON.stringify(a.evidence),JSON.stringify(a.metadata),a.contentHash,a.discoveredAt]);}
 async list():Promise<CapabilityAsset[]>{const r=await this.pool.query(`select * from capability_assets order by name`);return r.rows.map(x=>({id:x.id,name:x.name,tags:x.tags,maturity:x.maturity,evidence:x.evidence,executionZones:x.execution_zones,sourceType:x.source_type,sourceUri:x.source_uri,description:x.description,metadata:x.metadata_json,contentHash:x.content_hash,discoveredAt:new Date(x.discovered_at).toISOString()}));}
 async saveMatches(opportunityId:string,matches:CapabilityMatch[]):Promise<void>{const c=await this.pool.connect();try{await c.query('begin');for(const m of matches)await c.query(`insert into capability_matches(opportunity_id,requirement_id,capability_id,score,disposition,rationale) values($1,$2,$3,$4,$5,$6) on conflict(opportunity_id,requirement_id) do update set capability_id=excluded.capability_id,score=excluded.score,disposition=excluded.disposition,rationale=excluded.rationale,created_at=now()`,[opportunityId,m.requirementId,m.capabilityId??null,m.score,m.disposition,m.rationale]);await c.query('commit');}catch(e){await c.query('rollback');throw e;}finally{c.release();}}
}
