import type { BrainPlan, BrainTask, BuildSpecification, CapabilityMatch, CapabilityRecord, PublicOpportunity, Requirement, TreasuryAnalysis } from './types.js';

const makeId=(prefix:string,value:string)=>`${prefix}-${value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,64)}`;
const sentences=(opportunity:PublicOpportunity)=>`${opportunity.summary}\n${opportunity.rawText??''}`.split(/(?<=[.!?])\s+|\n+/).map(v=>v.trim()).filter(v=>v.length>=24);
function category(statement:string):Requirement['category']{const t=statement.toLowerCase();if(/security|cyber|clearance|encryption/.test(t))return'security';if(/standard|comply|certif|regulation/.test(t))return'compliance';if(/test|demonstrat|verify|validation|acceptance/.test(t))return'validation';if(/deliver|schedule|deadline|milestone/.test(t))return'delivery';if(/interface|interoperab|api|integration|open architecture/.test(t))return'interface';if(/data rights|intellectual property|license/.test(t))return'data-rights';if(/capacity|range|speed|accuracy|latency|throughput|availability/.test(t))return'performance';return'functional';}

export function parseOpportunity(opportunity:PublicOpportunity):TreasuryAnalysis{
 const candidates=sentences(opportunity);
 const statements=candidates.filter(s=>/\b(must|shall|required|requires|minimum|maximum|eligible|deliver|demonstrat|comply|capable)\b/i.test(s));
 const requirements=statements.map((statement,index)=>({id:`${opportunity.externalId}-REQ-${String(index+1).padStart(3,'0')}`,statement,category:category(statement),mandatory:/\b(must|shall|required|minimum|maximum)\b/i.test(statement),sourceEvidence:statement}));
 const reviewRequired=opportunity.provenance.some(s=>s.authority!=='official')||requirements.length===0;
 return {opportunityId:opportunity.externalId,missionProblem:opportunity.summary,desiredOutcomes:candidates.filter(s=>/\b(outcome|goal|objective|improve|reduce|increase|enable|provide)\b/i.test(s)).slice(0,8),requirements,standards:candidates.filter(s=>/\b(ISO|NIST|FAR|DFARS|NDAA|ASTM|IEEE|OSHA|standard|regulation)\b/i.test(s)),deliverables:candidates.filter(s=>/\b(deliverable|report|prototype|system|plan|documentation|training)\b/i.test(s)).slice(0,12),evaluationCriteria:candidates.filter(s=>/\b(evaluat|selection|criterion|score|merit|past performance|price)\b/i.test(s)),risks:[...(opportunity.deadline?[]:['No deadline was captured.']),...(opportunity.provenance.some(s=>s.authority!=='official')?['Non-official provenance requires verification.']:[]),...(requirements.length===0?['No explicit requirements were extracted; attachment review is required.']:[])],fitTags:Array.from(new Set(candidates.flatMap(s=>s.toLowerCase().match(/\b(ai|autonomy|cybersecurity|sensor|digital twin|energy|health|logistics|aerospace|maritime|infrastructure|data|software|hardware)\b/g)??[]))),confidence:Math.max(.2,Math.min(.95,.45+requirements.length*.04-(reviewRequired?.15:0))),reviewRequired};
}

export function generateBuildSpecification(a:TreasuryAnalysis):BuildSpecification{const mandatory=a.requirements.filter(r=>r.mandatory);return{specificationId:makeId('SPEC',a.opportunityId),opportunityId:a.opportunityId,objective:a.missionProblem,components:Array.from(new Set([...a.fitTags.map(t=>`${t} subsystem`),...mandatory.map(r=>`Component satisfying ${r.id}`)])),interfaces:a.requirements.filter(r=>r.category==='interface').map(r=>r.statement),tests:(a.requirements.filter(r=>r.category==='validation').map(r=>`Verify: ${r.statement}`)).concat(mandatory.map(r=>`Acceptance test for ${r.id}`)),acceptanceCriteria:mandatory.map(r=>r.statement),standards:a.standards,evidenceRequired:['Requirements traceability matrix','Architecture and interface documentation','Test plan and test results','Compliance evidence','Configuration and provenance manifest'],executionZones:['OpenClaw','Nemotron','Hermes','Docker','Manus'],approvalState:'draft'};}

export function createBrainPlan(s:BuildSpecification):BrainPlan{const tasks:BrainTask[]=[{id:'TASK-001',title:'Research authoritative requirements and attachments',kind:'research',dependsOn:[],acceptanceCriteria:['All requirements cite authoritative source evidence'],executionZone:'OpenClaw'},{id:'TASK-002',title:'Produce architecture and traceability',kind:'design',dependsOn:['TASK-001'],acceptanceCriteria:s.acceptanceCriteria,executionZone:'Nemotron'},{id:'TASK-003',title:'Implement software and integration components',kind:'software',dependsOn:['TASK-002'],acceptanceCriteria:s.interfaces,executionZone:'Docker'},{id:'TASK-004',title:'Run simulations and verification tests',kind:'simulation',dependsOn:['TASK-003'],acceptanceCriteria:s.tests,executionZone:'Hermes'},{id:'TASK-005',title:'Assemble review-ready evidence',kind:'documentation',dependsOn:['TASK-004'],acceptanceCriteria:s.evidenceRequired,executionZone:'Manus'}];return{planId:makeId('PLAN',s.specificationId),specificationId:s.specificationId,tasks,externalActionsBlocked:true};}

export function matchCapabilities(a:TreasuryAnalysis,capabilities:CapabilityRecord[]):CapabilityMatch[]{return a.requirements.map(r=>{const tokens=new Set(r.statement.toLowerCase().match(/[a-z0-9-]{4,}/g)??[]);const ranked=capabilities.map(c=>({c,score:c.tags.filter(t=>tokens.has(t.toLowerCase())).length/Math.max(1,c.tags.length)})).sort((x,y)=>y.score-x.score);const best=ranked[0],score=best?.score??0;return{requirementId:r.id,capabilityId:score>0?best.c.id:undefined,score,disposition:score>=.7?'reuse':score>=.35?'adapt':'build',rationale:score>0?`Matched ${best.c.name} using normalized capability tags.`:'No supported capability match was found; build or partner analysis is required.'};});}

export function assertExternalActionAuthorized(action:'submit_offer'|'file_patent'|'commit_funds'|'external_representation',authorizationToken?:string):void{if(!authorizationToken?.startsWith('AEGENTIX-AUTH-'))throw new Error(`${action} blocked: explicit AEGENTIX authorization is required.`);}
export function runInternalPipeline(opportunity:PublicOpportunity,capabilities:CapabilityRecord[]=[]){const analysis=parseOpportunity(opportunity);const specification=generateBuildSpecification(analysis);return{analysis,specification,plan:createBrainPlan(specification),matches:matchCapabilities(analysis,capabilities)};}
