export type OpportunityType = 'RFI'|'RFP'|'RFQ'|'IFB'|'BAA'|'CSO'|'OTA'|'SBIR'|'STTR'|'GRANT'|'COOPERATIVE_AGREEMENT'|'PRIZE'|'CHALLENGE'|'SOURCES_SOUGHT'|'FORECAST'|'LICENSING'|'PARTNERSHIP'|'SUBCONTRACT'|'OTHER';
export interface SourceProvenance { system:string; authority:'official'|'partner'|'aggregator'; url:string; retrievedAt:string; contentHash?:string; attachmentUrls?:string[]; }
export interface PublicOpportunity { schemaVersion:'1.0.0'; eventId:string; externalId:string; title:string; issuer:string; jurisdiction:string; opportunityType:OpportunityType; publicationDate?:string; updateDate?:string; deadline?:string; value?:{amount?:number;currency?:string;text?:string}; eligibility:string[]; setAside?:string; location?:string; submissionMethod?:string; requiredRegistrations:string[]; summary:string; rawText?:string; provenance:SourceProvenance[]; }
export interface Requirement { id:string; statement:string; category:'functional'|'performance'|'interface'|'compliance'|'delivery'|'security'|'data-rights'|'validation'; mandatory:boolean; sourceEvidence:string; }
export interface TreasuryAnalysis { opportunityId:string; missionProblem:string; desiredOutcomes:string[]; requirements:Requirement[]; standards:string[]; deliverables:string[]; evaluationCriteria:string[]; risks:string[]; fitTags:string[]; confidence:number; reviewRequired:boolean; }
export interface BuildSpecification { specificationId:string; opportunityId:string; objective:string; components:string[]; interfaces:string[]; tests:string[]; acceptanceCriteria:string[]; standards:string[]; evidenceRequired:string[]; executionZones:Array<'OpenClaw'|'Nemotron'|'Hermes'|'Docker'|'Manus'>; approvalState:'draft'|'technical_review'|'authorized'; }
export interface BrainTask { id:string; title:string; kind:'research'|'design'|'software'|'hardware'|'simulation'|'compliance'|'test'|'documentation'; dependsOn:string[]; acceptanceCriteria:string[]; executionZone:BuildSpecification['executionZones'][number]; }
export interface BrainPlan { planId:string; specificationId:string; tasks:BrainTask[]; externalActionsBlocked:true; }
export interface CapabilityRecord { id:string; name:string; tags:string[]; maturity:string; evidence:string[]; executionZones:BuildSpecification['executionZones']; }
export interface CapabilityMatch { requirementId:string; capabilityId?:string; score:number; disposition:'reuse'|'adapt'|'build'|'partner'; rationale:string; }
